version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file:
      - db.env
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8080:80
      # open 443 for https
      - 443:443
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      # setup a certificate bot for https
      - ./setupcertbot.sh:/usr/local/bin/setupcertbot.sh
    restart: always
    env_file:
      - wordpress.env
    environment:
      WORDPRESS_DB_HOST: db:3306
volumes:
  db_data:

